# Generated by Django 5.0.3 on 2024-03-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateField()),
                ('priority', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=10)),
            ],
        ),
    ]
